//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bill
    {
        public int CustId { get; set; }
        public int InvoiceId { get; set; }
        public int AutoInvoiceID { get; set; }
        public decimal SGST { get; set; }
        public decimal CGST { get; set; }
    }
}
